### ISSUE TITLE
Run a sequence of tests from a YAML file

### ISSUE THREAD

**Issue by JamesBalazs** [JamesBalazs/lode#5]
It should be possible to run a sequence of load tests from a YAML file, where the keys/values of each job correspond to flags supported by the `lode test` command.

Example format:
```
tests:
  - url: https://www.google.co.uk
    method: GET
    concurrency: 4
    freq: 10
    maxrequests: 20
  - url: https://abc.xyz/
    method: GET
    concurrency: 2
    delay: 0.5s
    maxrequests: 4
```
